#!/bin/bash

echo "🎯 Multi-User Chat Testing Guide"
echo "================================="
echo ""
echo "📝 Step 1: Open this in a separate terminal:"
echo "   docker compose logs visa-web -f | grep 'verification code'"
echo ""
echo "📝 Step 2: Open multiple browser windows:"
echo "   • Normal Window: http://localhost:8000"
echo "   • Incognito #1:  Cmd+Shift+N → http://localhost:8000"
echo "   • Incognito #2:  Cmd+Shift+N → http://localhost:8000"
echo ""
echo "📝 Step 3: Login as different users:"
echo "   • Window 1: alice@example.com (Alice)"
echo "   • Window 2: bob@example.com (Bob)"
echo "   • Window 3: charlie@example.com (Charlie)"
echo ""
echo "📝 Step 4: Watch verification codes in the logs terminal"
echo ""
echo "📝 Step 5: Start chatting!"
echo ""
echo "✨ What to test:"
echo "   ✅ All users see each other online"
echo "   ✅ Messages appear in real-time"
echo "   ✅ Avatars show unique colors"
echo "   ✅ Profile updates work live"
echo "   ✅ Message grouping works"
echo ""
echo "🚀 Ready? Press Ctrl+C to exit, or run:"
echo "   docker compose logs visa-web -f | grep 'verification code'"
echo ""
